### PR TITLE
Release #major

### PR DESCRIPTION
**Pull request by armandfardeau**

### CODE REVIEW

**Comment by virgile-dev** [comment]
@quentinleport awesome work !
I just have a minor comment that can be address in a later version.  
In Decidim 0.22 stable and above the `endorsements/total_count` column is under `endorsements`. 
You might wanna take this into consideration as it causes the script to scratch. Could you make it work for both cases ?

**Comment by virgile-dev** [comment]
@quentinleport  I also noticed that you use French in several places in your code. We have to decide wheither the project is all in English or all in French. 

I'm thinking of the sorting arguments "supports" instead of endorsements, "commentaires" instead of comments. 
The column headings in the csv, the entities in bold in the docx. 

What do you think, will the consultants will be OK if we go for all english  or will it mess with their work?

**Review by armandfardeau — COMMENTED** [review]
Everything seems good. Good to me.

**Comment by virgile-dev** [comment]
Ok @quentinleport let's merge !
Can you also draft a release note for v1 specifying the included features (it can be a copy paste from readme)?

**Review by quentinleport — APPROVED** [review]

**Pull request merged**
